spring.application.name=lab31_03
spring.datasource.generate-unique-name=false
spring.datasource.name=people

spring.jpa.show-sql=true
spring.datasource.username=sa
spring.datasource.password=1234
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
